// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCldhTvZ0tecuDH8qZy4nd_FJQa23PTMO8',
    appId: '1:673342381546:web:6e3b18d956f50910ffe693',
    messagingSenderId: '673342381546',
    projectId: 'newsapp-b479a',
    authDomain: 'newsapp-b479a.firebaseapp.com',
    storageBucket: 'newsapp-b479a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7x1B0y4XMSMvfgGcO6vlVzlwmAMg2aS0',
    appId: '1:673342381546:android:4876a50a62290d4bffe693',
    messagingSenderId: '673342381546',
    projectId: 'newsapp-b479a',
    storageBucket: 'newsapp-b479a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyX-C5f2CjSQyzh4Bp6G2NRAVNHrnv31I',
    appId: '1:673342381546:ios:8837cc1f60d62d52ffe693',
    messagingSenderId: '673342381546',
    projectId: 'newsapp-b479a',
    storageBucket: 'newsapp-b479a.firebasestorage.app',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyX-C5f2CjSQyzh4Bp6G2NRAVNHrnv31I',
    appId: '1:673342381546:ios:8837cc1f60d62d52ffe693',
    messagingSenderId: '673342381546',
    projectId: 'newsapp-b479a',
    storageBucket: 'newsapp-b479a.firebasestorage.app',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCldhTvZ0tecuDH8qZy4nd_FJQa23PTMO8',
    appId: '1:673342381546:web:5849df642d387c8effe693',
    messagingSenderId: '673342381546',
    projectId: 'newsapp-b479a',
    authDomain: 'newsapp-b479a.firebaseapp.com',
    storageBucket: 'newsapp-b479a.firebasestorage.app',
  );
}
